### PR TITLE
add scripts to build entry point file for browser

### PR DESCRIPTION
**Pull request by imyelo**
An es5 javascript file built with rollup and babel can be very helpful on browser-side.

The `browser` field in `package.json` is following https://docs.npmjs.com/files/package.json#browser .

### CODE REVIEW

**Comment by imyelo** [comment]
BTW. This PR could fix https://github.com/imyelo/pokequest-wiki/issues/1 .

**Comment by targos** [comment]
@stropitek

**Comment by stropitek** [comment]
Thanks!

**Comment by stropitek** [comment]
published v1.1.0

**Pull request merged**
